module.exports = {
  "env": { "es6": false },
  "rules": {
    "block-scoped-var": 0,
    "block-spacing": 0,
    "comma-spacing": 0,
    "eol-last": 0,
    "eqeqeq": 0,
    "func-names": 0,
    "key-spacing": 0,
    "keyword-spacing": 0,
    "lines-around-directive": 0,
    "nested-ternary": 0,
    "new-cap": 0,
    "no-cond-assign": 0,
    "no-mixed-operators": 0,
    "no-nested-ternary": 0,
    "no-param-reassign": 0,
    "no-sequences": 0,
    "no-shadow": 0,
    "no-undef": 0,
    "no-unused-expressions": 0,
    "no-return-assign": 0,
    "no-var": 0,
    "no-void": 0,
    "one-var": 0,
    "prefer-arrow-callback": 0,
    "prefer-rest-params": 0,
    "prefer-template": 0,
    "object-curly-spacing": 0,
    "one-var-declaration-per-line": 0,
    "quotes": 0,
    "semi": 0,
    "semi-spacing": 0,
    "space-before-blocks": 0,
    "space-infix-ops": 0,
    "space-before-function-paren": 0,
    "strict": 0,
    "vars-on-top": 0,
    "wrap-iife": 0,
    "yoda": 0
  }
};